apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Broadcaster
  - ../../broadcaster/manifests/configmap.yaml
  - ../../broadcaster/manifests/deployment.yaml

  # Todo backend (service + deployment)
  - ../../todo-backend/manifests/todo-backend-config.yaml
  - ../../todo-backend/manifests/todo-backend.yaml

  # Postgres (service + statefulset + config)
  - ../../todo-backend/manifests/todo-postgres-config.yaml
  - ../../todo-backend/manifests/todo-postgres-statefulset.yaml
